name = "plantpal"
main = "src/index.ts"                # entry point to your Worker
compatibility_date = "2025-12-27"   # current date in YYYY-MM-DD

[[durable_objects]]
name = "PLANT_DO"
class_name = "PlantDO"

# optional: environment variables
[vars]